### ISSUE TITLE
Getting a error when i try to run yarn db:push

### ISSUE THREAD

**Issue by RvDstudio** [Accretence/next-prisma-tailwind-ecommerce#1]
Below you see the output of my terminal

USER@DESKTOP-K4G6NPR MINGW64 /c/Development/next-prisma-tailwind-ecommerce/packages/database (main)
$ yarn db:generate
yarn run v1.22.15
$ npx prisma generate
Prisma schema loaded from prisma\schema.prisma
Error: Could not resolve prisma and @prisma/client in the current project. Please install them with yarn add prisma -D and yarn add @prisma/client, and rerun npx "prisma generate" 🙏.
error Command failed with exit code 1.

Let me know if you need more info.

**Comment by Accretence** [comment]
Have you installed the dependencies inside the `packages/database` subdirectory?

**Comment by RvDstudio** [comment]
> Have you installed the dependencies inside the `packages/database` subdirectory?

Thanks for the quick response, It is working now.

**Comment by RvDstudio** [comment]
> Have you installed the dependencies inside the `packages/database` subdirectory?

Thanks for the quick response, It is working now.
