### ISSUE TITLE
Issues with production build & start

### ISSUE THREAD

**Issue by furkankarayel** [Accretence/next-prisma-tailwind-ecommerce#3]
I am not able to deploy the app. So far I have set and tested the smtp and database url.
The db was successfully created and after some tsconfig problems I was able to run the prisma/seeds.ts to fill thedb with dummy data. 
Locally I have the problem that login does not work. The seeds admin credentials have been changed though.I am receiving the OTP but im not redirected to the next page. 
Is it because the JWT Secret is missing?

When I was trying to deploy the app to vercel, I have been getting too many errors with eslint and module import errors. I have fixed the eslint errors quick and dirty by temporary putting eslint off.

I want to know if there are common tips you may give to notice when building for production. It is all good when I run the development environment. 
Is the current app limited in functionality or are the full features working already? (Because the demo app shows limited functionality aswell)

What is the idea behind the admin and storefront directories? I could not really read it somewhere.

Thank you in advance!

![Bildschirmfoto 2023-12-29 um 23 19 51](https://github.com/Accretence/next-prisma-tailwind-ecommerce/assets/47307090/ec3afa1e-d6d7-47fb-a8c4-d8aaccde6340)

![Bildschirmfoto 2023-12-29 um 23 20 06](https://github.com/Accretence/next-prisma-tailwind-ecommerce/assets/47307090/1f3aad95-0ffc-43e6-8b0e-867924137d08)

**Comment by Accretence** [comment]
I've forgotten to mention the root directory step in the README.md file. There are 2 standalone Next.js apps in this project, therefore you need to deploy 2 apps in Vercel, one for each app in the `apps` directory.

There is a Root Directory option in your project's settings in the Vercel Dashboard where you can specify what directory Vercel should use to build your app.

![image](https://github.com/Accretence/next-prisma-tailwind-ecommerce/assets/45223699/f5adc1ac-9dbb-46cb-bb6e-a8db15883348)

**Comment by furkankarayel** [comment]
I have been successful with the root directory tip. I could login to the admin panel after putting the jwt_secret key but the login in the storefront was not working anyway. Another thing I have noticed was that deleted products in the db haven‘t been updated in the ui straight after deletion. 
Are these points fixed in the stable versions? Probably I have cloned the development version. Thank you in advance.

**Comment by Accretence** [comment]
> I have been successful with the root directory tip. I could login to the admin panel after putting the jwt_secret key but the login in the storefront was not working anyway. Another thing I have noticed was that deleted products in the db haven‘t been updated in the ui straight after deletion. Are these points fixed in the stable versions? Probably I have cloned the development version. Thank you in advance.

The project has only 1 branch, there is no development version. There are no problems with the login process and no problems with the CRUD operations on the admin dashboard. There is no caching implemented so if the document is deleted on database it should be instantly removed from the admin UI and the storefront, but I'll try and take a second look at it and fix it if there are any issues.

**Comment by furkankarayel** [comment]
Nice thank you, I will also take a look too because I have deleted the vercel instances. Could you define strict steps to follow for a complete setup of the admin and storefront instances please, so I would check if I have forgotten something.
